
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20231130.0.0"
  config.vm.network "private_network", ip: "192.168.33.30"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "playbook.yml"
  #end
end
