- hosts: docker
  become: yes
  vars:
    ip_address: '192.168.33.30'
    hostname: 'wazuh'
  tasks:
    - name: Add entry for wazuh to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: '{{ ip_address }} {{ hostname }}'
        state: present

    - name: Download wazuh-agent
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.2.7-1_amd64.deb
        dest: /tmp/wazuh-agent-4.2.7.deb

    - name: Install wazuh-agent
      ansible.builtin.shell:
        cmd: WAZUH_MANAGER='wazuh' WAZUH_AGENT_GROUP='default' dpkg -i /tmp/wazuh-agent-4.2.7.deb

    - name: Reload systemctl daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable wazuh-agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start wazuh-agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started